name: Release to itch.io

on:
  push:
    tags:
    - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./VagabondRL

    steps:
    - uses: actions/checkout@v2
      with:
        repository: pandepic/ElementEngine
        path: ./ElementEngine    
    - uses: actions/checkout@v2
      with:
        repository: pandepic/VagabondRL
        path: ./VagabondRL
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Build Windows
      run: dotnet publish GameClient/GameClient.csproj -r win-x64 -c Release --output build-windows
    - name: Build Osx
      run: dotnet publish GameClient/GameClient.csproj -r osx-x64 -c Release --output build-osx
    - name: Build Linux
      run: dotnet publish GameClient/GameClient.csproj -r linux-x64 -c Release --output build-linux
    - name: Clean NetCoreBeauty
      run: find . -name 'NetCoreBeauty' -type f -delete
    - name: Publish Windows build to itch.io
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: windows
        ITCH_GAME: vagabondrl
        ITCH_USER: pandepic
        PACKAGE: ./VagabondRL/build-windows
    - name: Publish OSX build to itch.io
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: osx
        ITCH_GAME: vagabondrl
        ITCH_USER: pandepic
        PACKAGE: ./VagabondRL/build-osx
    - name: Publish Linux build to itch.io
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: linux
        ITCH_GAME: vagabondrl
        ITCH_USER: pandepic
        PACKAGE: ./VagabondRL/build-linux
